name: Testing

# Require testing for pull requests to main branch
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: actions/checkout@v2
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

  # JOB to build and test backend code
  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js (latest)
        uses: actions/setup-node@v1
        with:
          node-version: latest
      - run: cd backend/
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present

  # JOB to build and test frontend code
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js (latest)
        uses: actions/setup-node@v1
        with:
          node-version: latest
      - run: cd frontend/
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present
